### ISSUE TITLE
Completion candidates starting with `@` duplicate the `@` character when selected (eglot)

### ISSUE THREAD

**Issue by ryoung786** [lexical-lsp/lexical#351] opened 2023-08-29 17:18 UTC
Triggering completion suggestions that start with `@` appear correct:
<img width="464" alt="Screenshot 2023-08-29 at 11 12 24 AM" src="https://github.com/lexical-lsp/lexical/assets/122238/1d7a5db4-2f77-47b1-a097-8fbce2593e53">

But when a candidate is selected and it inserts the text, the first `@` is duplicated:
<img width="248" alt="Screenshot 2023-08-29 at 11 12 52 AM" src="https://github.com/lexical-lsp/lexical/assets/122238/45a9b536-4252-4758-b02e-f2aaa42f1b0b">

This seems to be the case for any code completion starting with `@`, and happens regardless of how much of a prefix you've already typed before selecting a candidate.

The resulting eglot log from the above interaction is [here](https://gist.github.com/ryoung786/98ec15c4e65d95b850f5c6f92ef26af9)

### Setup
**lexical version**: [main branch, commit d9dcae41e0](https://github.com/lexical-lsp/lexical/commit/d9dcae41e03254f589a7c44e058013fe098043b4), compiled with elixir **v1.15.4-otp-26**
**emacs**: v30.5
**eglot**: built-in

**Comment by ryoung786** [comment] 2023-09-16 16:59
This behavior also occurs for structs and the `%` character.

**Comment by scohen** [comment] 2023-09-17 21:58
This is so odd; lsp-mode, vscode and nvim don't have this issue.

**Comment by zachallaun** [comment] 2023-10-12 22:53
Want wanted to note that the cause of this has been found and a fix should be merged soon. :)

**Closed** 2023-10-15 15:39 UTC

**Comment by katafrakt** [comment] 2023-10-16 12:14
Awesome. I can confirm that the issue is gone now. Thanks for all your hard work!

**Comment by ryoung786** [comment] 2023-10-19 01:14
Hi, I can also confirm that the `@` duplication is fixed.  🎉 

However structs changed from duplicating the leading `%` to now duplicating the first letter of the struct.  Example:
- *expected*: `%Foo{}`
- *was*: `%%Foo{}`
- *now*: `FFoo{}`

**Comment by scottming** [comment] 2023-10-19 01:48
@ryoung786 

I can't replicate this:

<img width="596" alt="image" src="https://github.com/lexical-lsp/lexical/assets/12830256/5358f3e0-b117-41e2-adde-8b2705503e01">

**Comment by ryoung786** [comment] 2023-10-19 02:25
![struct](https://github.com/lexical-lsp/lexical/assets/122238/d08a6a58-df5d-47dd-8cfb-502161035b67)

Maybe it's only an issue with emacs/eglot?  Here's the [eglot log](https://gist.github.com/ryoung786/c6919b836366079b0b7ceee9f87e9dae) from the dummy session seen in the above gif.

**Comment by zachallaun** [comment] 2023-10-19 11:49
Thank you for the gif and log! Here's the offending response:

```
[client-request] (id:25) Wed Oct 18 22:22:12 2023:
(:jsonrpc "2.0" :id 25 :method "textDocument/completion" :params
	  (:textDocument
	   (:uri "file:///Users/ryoung/dev/scratch/foo/lib/foo.ex")
	   :position (:line 11 :character 5) :context (:triggerKind 1)))
[server-reply] (id:25) Wed Oct 18 22:22:12 2023:
(:id 25 :result
     [(:label "Foo" :kind 22 :detail "Foo" :textEdit
	      (:range
	       (:start (:line 11 :character 3) :end
		       (:line 11 :character 5))
	       :newText "Foo{$1}")
	      :insertTextFormat 2 :sortText "099_Foo")]
     :jsonrpc "2.0")
```

@scohen I could use your help here. The start character is 3, but it's 0-indexed at this point, right? That looks like the correct range to me if so.

**Comment by scohen** [comment] 2023-10-19 15:11
correct, LSP is 0 indexed, and it does look to me like this is the correct range. 
I'm using emacs with lsp-mode, and I don't see this issue. I suspect this is a bug or misunderstanding in eglot. I wonder if it is still interpolating "words" even when confronted with an edit range.

**Comment by scohen** [comment] 2023-10-19 15:12
Also, I tried eglot a while back and switched back to lsp-mode, and it might have been issues like this that caused the switch. I also couldn't figure out how to report a bug.

**Comment by ryoung786** [comment] 2024-01-29 01:17
To close the loop on this, I updated today to eglot 1.17 and all the duplicate character issues for structs are gone.  I suspect this was related to https://github.com/joaotavora/eglot/issues/1349 which made it into that release.
