### ISSUE TITLE
LSP Crash on start after 0.4

### ISSUE THREAD

**Issue by oliveigah** [lexical-lsp/lexical#448] opened 2023-10-25 00:28 UTC
I think this bug is back on release 0.4 https://github.com/lexical-lsp/vscode-lexical/issues/24

If I compile lexical using the same elixir version of the project's `.tool-versions` and set the proper path on the extension config, everything works fine.

If I use a different elixir version I get this:

```
Detected Elixir through asdf: /home/oliveigah/.asdf/installs/elixir/1.14.4-otp-25/bin/elixir
** (ArgumentError) could not load module LXSourceror due to reason :badfile
    (elixir 1.14.4) lib/code.ex:1581: Code.ensure_loaded!/1
    (elixir 1.14.4) lib/enum.ex:975: Enum."-each/2-lists^foreach/1-0-"/2
    lib/lexical/server/boot.ex:24: LXical.Server.Boot.start/0
    /home/oliveigah/.config/Code/User/globalStorage/lexical-lsp.lexical/lexical_install/lexical/bin/boot.exs:23: (file)
[Error - 9:26:37 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 9:26:37 PM] Connection to server got closed. Server will restart.
```

**Comment by Blond11516** [comment] 2023-10-25 02:11
Hi @oliveigah! I've transferred your issue over here because I believe it's stemming from Lexical itself, not from the vscode extension. It'll be easier for the core team to help you and coordinate a fix if necessary from here.

**Comment by scohen** [comment] 2023-10-25 04:01
@zachallaun

**Comment by scohen** [comment] 2023-10-25 13:18
@oliveigah if you're compiling lexical yourself, you need to select the lowest versions of elixir and erlang that your projects need. 

Can you be specific about which versions you used to compile, and which versions your projects use?

**Comment by oliveigah** [comment] 2023-10-25 13:31
Initially I did not compile it my self, I just use default behaviour of the vs-code extension that AFAIK automatically fetch the latest version and compile it.

The context is the following:

1 - elixir 1.15.6-otp-26 as the global version
2 - Open a project with a tool-versions elixir 1.14.4-otp-25
3 - Crash happen

If I manually compile it using elixir 1.14.4-otp-25 and setup the vs-code extension properly, everything works fine (even keeping 1.15.6-otp-26 as global)

What I think is strange is that before the 0.4 release the vs-code extension worked just fine on this setup (1.15.6-otp-26 global, 1.14.4-otp-25 project)

In order to chek my understanding, if I need to use lexical on multiple projects I need to manually compile it using the lowest version?

Is there a way to identifiy the current folder tool-version and automatically recompile lexical using the proper version? If you guys think it is desriable and doable, with some guidance I can try to open a PR on it! Let me know! (:

**Comment by scohen** [comment] 2023-10-25 15:40
I see. 

> In order to chek my understanding, if I need to use lexical on multiple projects I need to manually compile it using the lowest version?

Correct

> Is there a way to identifiy the current folder tool-version and automatically recompile lexical using the proper version? 

🤔 I don't want to say "no" outright. there might be a way to create a "universal" build of lexical that includes beam files from all the different versions, but I think it  would be very complicated to set up and use. 

I think there's something wrong with the build though, we compile it under a lower version than you have, so it _should_ work.

**Comment by scohen** [comment] 2023-10-25 15:55
@oliveigah Can you re-dowload and try again? I think something was messed up with the build. I was able to reproduce the problem locally by downloading the released version, then trying to start it. 
I re-ran the build, re-downloaded the artifact and it worked.

**Closed** 2023-10-25 16:23 UTC

**Comment by oliveigah** [comment] 2023-10-25 16:34
I think you are right. Thanks for the fast response! (:
