### ISSUE TITLE
Indexing never finishes due to a FunctionClauseError

### ISSUE THREAD

**Issue by Terbium-135** [lexical-lsp/lexical#527] opened 2023-12-25 08:03 UTC
- Deleted projects index file
- Started VSCode
- Lexical rebuilds/compiles the project
- Indexing started after the compile has been finished
- Indexing never finishes
- VSCode shows;
![reindexing](https://github.com/lexical-lsp/lexical/assets/29901271/2771fb83-bc7e-4db8-bda1-cfd86f4e28f2)

**Versions used:**
```
Erlang/OTP 26 [erts-14.1.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit]
Elixir 1.15.7 (compiled with Erlang/OTP 26)
```

Lexical main as of 2023-12-24

**Project.log:**
```
2023-12-24T19:56:23.329182+01:00 error: Task #PID<0.3056.0> started from #PID<0.2831.0> terminating, ** (FunctionClauseError) no function clause matching in :elixir_aliases.do_concat/2, (elixir 1.15.7) src/elixir_aliases.erl:150: :elixir_aliases.do_concat([{:unquote, [closing: [line: 97, column: 33], line: 97, column: 18], [{:backend, [line: 97, column: 26], nil}]}, :Number, :System], "Elixir"), (elixir 1.15.7) src/elixir_aliases.erl:138: :elixir_aliases.concat/1, (lx_remote_control 0.3.0) lib/lexical/remote_control/analyzer.ex:92: LXical.RemoteControl.Analyzer.expand_alias/3, (lx_remote_control 0.3.0) lib/lexical/remote_control/search/indexer/extractors/function_reference.ex:135: LXical.RemoteControl.Search.Indexer.Extractors.FunctionReference.entry/6, (lx_remote_control 0.3.0) lib/lexical/remote_control/search/indexer/extractors/function_reference.ex:50: LXical.RemoteControl.Search.Indexer.Extractors.FunctionReference.extract/2, (lx_remote_control 0.3.0) lib/lexical/remote_control/search/indexer/source/reducer.ex:76: anonymous fn/2 in LXical.RemoteControl.Search.Indexer.Source.Reducer.apply_extractors/2, (elixir 1.15.7) lib/enum.ex:2510: Enum."-reduce/3-lists^foldl/2-0-"/3, (lx_remote_control 0.3.0) lib/lexical/remote_control/search/indexer/quoted.ex:8: anonymous fn/2 in LXical.RemoteControl.Search.Indexer.Quoted.index/1, Function: &:erlang.apply/2, Args: [#Function<13.42179829/1 in LXical.RemoteControl.Search.Indexer.async_chunks/3>,
[...]
```

**Comment by zachallaun** [comment] 2023-12-25 16:30
I believe this is a duplicate of #520.

**Comment by scohen** [comment] 2023-12-27 01:49
Closing as duplicate

**Closed** 2023-12-27 01:49 UTC
Labels: duplicate
