### ISSUE TITLE
Undefined function gettext/1 in `app.html.heex`

### ISSUE THREAD

**Issue by Terbium-135** [lexical-lsp/lexical#547] opened 2024-01-05 16:29 UTC
While editing `app.html.heex` (I guess this will happen editing any heex file) an error is shown:

![gettext-error](https://github.com/lexical-lsp/lexical/assets/29901271/85452c61-7657-4d6c-829d-438f65dd5731)

After a recompile the error is gone.
Reporting this more or less for completeness

**Comment by scottming** [comment] 2024-01-07 03:18
@Terbium-135 Once you save the file, the error diagnostics will disappear, right?

I think this is a known issue, https://github.com/lexical-lsp/lexical/issues/495#issuecomment-1828853060

**Comment by Terbium-135** [comment] 2024-01-07 11:21
Aye, the diagnostics are disappearing on a save.

**Comment by scohen** [comment] 2024-01-09 18:42
Duplicate of #495

**Closed by scohen** 2024-01-09 18:42 UTC
Labels: duplicate
